# ===============================
# COMMON / SHARED CONFIGURATION
# ===============================
spring.application.name=hotel

# Default active profile (override with --spring.profiles.active=prod)
spring.profiles.active=dev

# ===============================
# JWT & SECURITY
# ===============================
jwt.secret-key=${JWT_SECRET_KEY:GENERATE}
jwt.expiration-time=900000
refresh-token.expiration-time=86400000

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# DEFAULT VALUES
default.manager_username=${DEFAULT_MANAGER_USERNAME:manager}
default.manager_password=${DEFAULT_MANAGER_PASSWORD:stupid_pass}

# OTP
otp.length=6
otp.expiry-minutes=5
otp.resend-cooldown-seconds=60
otp.max-attempts=5

app.security.skip-activated-urls=/api/v1/otp/send,/api/v1/users/activate-by-otp