# ===============================
# COMMON / SHARED CONFIGURATION
# ===============================
spring.application.name=hotel

# Default active profile (override with --spring.profiles.active=prod)
spring.profiles.active=dev

# ===============================
# JWT & SECURITY
# ===============================
jwt.secret-key=3454632352345436457564523423432423423453456456756765
jwt.expiration-time=900000
refresh-token.expiration-time=86400000

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false