spring.application.name=hotel

jwt.secret-key=3454632352345436457564523423432423423453456456756765
jwt.expiration-time=900000
refresh-token.expiration-time=86400000

logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate.SQL=DEBUG

# ===============================
# H2 IN-MEMORY CONFIGURATION
# ===============================

# 1. Kết nối tới H2 trong RAM
spring.datasource.url=jdbc:h2:mem:hoteldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Cấu hình H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Cần thiết để H2 Console hiển thị được khi dùng Spring Security
spring.h2.console.settings.web-allow-others=true

# 3. JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true